### ISSUE TITLE
Question : Do you really need to install the 

### ISSUE THREAD

**Issue by Valombreuse** [s0md3v/sd-webui-roop#103]
Hi,
According to the user guide : 
On Windows, download and install [Visual Studio](https://visualstudio.microsoft.com/downloads/). During the install, make sure to include the Python and C++ packages.
If you only check Python and C++ Desktop, it makes a 9,11 Gb installation. That is quite large for just the use of a single plug-in.
My question is : are there optional contents in the C++ package that are not mandatory and can be unchecked to lighten the installation ?

Thanks beforehand for your answer :)

PogS

**Comment by DmytroSokhach** [comment]
Assuming that A1111 is already installed and working, so system already has Python installation:
It is enough to install Visual Studio Build Tools https://visualstudio.microsoft.com/visual-cpp-build-tools/
Only select "**Desktop Development with C++**" under _Workloads -> Desktop & Mobile_.
**Important Note:** if you had it installed previously, update installer then click it once more, so it will install fresh components.

![image](https://github.com/s0md3v/sd-webui-roop/assets/2741620/a8a7511e-ad02-4e64-a50e-feadb33873bf)

**Comment by pulth** [comment]
![image](https://github.com/s0md3v/sd-webui-roop/assets/76142591/1a2facf4-9577-4579-857b-60d839146f4a)

I have these packages installed that are greater than 14.0. Should these work? I really don't want to use several gigabytes of disk space in bloatware.

**Comment by DmytroSokhach** [comment]
@pulth according to this https://github.com/s0md3v/roop/issues/153 VS build tools are mandatory (you don't need full Visual Studio)
Also you could give a try and skip Windows 11 SDK and only install those:
![image](https://github.com/s0md3v/sd-webui-roop/assets/2741620/e23de95b-d01a-4147-8eeb-b5bc4ba6e081)

**Comment by 1kari-s** [comment]
Sure a great extension, but putting so much junk software (6-8gb) in the package is ridiculous. Authors of other extensions find a way not to clutter up the system.

**Comment by DmytroSokhach** [comment]
@1kari-s  _I'll share my understanding and since I'm not author, please take it with grain of salt._

Main dependency is https://github.com/deepinsight/insightface
`insightface==0.7.3`
it doesn't have pre-compiled binaries, at least for Windows, and everyone who installs it in local Python virtual environment is required to compile it using MSVS C++ Build Tools. That is how Python operates.
Once "insightface" publish the library in more common way, this repo as well as hundreds of others will not require compilation anymore.
