### ISSUE TITLE
tried deleting onnxruntime and installing onnxruntime-gpu for cpu-> gpu

### ISSUE THREAD

**Issue by wecreatestory** [s0md3v/sd-webui-roop#64]
It doesn't work for some reason.. wonder why?

**Comment by s0md3v** [comment]
roop will utilize GPU if the correct onnxruntime build is configured, nothing I can do here.

the GPU support isn't even mentioned anywhere in readme because those extra few microseconds you save don't matter . If you are doing something which you think needs that extra GPU power, try following [these instructions](https://github.com/s0md3v/roop/wiki/2.-Acceleration) but again, you are on your own.
