### ISSUE TITLE
Installed Extension - Updated - Doesn't Show Up 

### ISSUE THREAD

**Issue by Evilander** [s0md3v/sd-webui-roop#89]
I do not see roop anywhere - could it be because I am using the Kitchen theme or something?

**Comment by jackeyke** [comment]
I have the same problem!Help!

**Comment by CeraRalaz** [comment]
Do you have
ModuleNotFoundError: No module named 'insightface'
error?

I suppose this is an issue. Patiently w8ing for answer how to fix

**Comment by jackeyke** [comment]
> I have the same problem!Help!

Problem solved! You must resolve whatever error you are getting in your terminal.

**Comment by ajmrly** [comment]
I think this is likely incorrect install order by users? I think it was in my case. The workaround I tried was is adding the versions from the roop extension's requirements.txt file to the requirements.txt and requirements_versions.txt files in the \stable-diffusion-webui root folder so they get installed in the venv folders when the webui.bat is called.

eg. add the below lines to requirements_versions.txt
insightface==0.7.3
onnxruntime==1.15.0
diffusers==0.17.1

If needed, you could add the below to the requirements.txt version in the \stable-diffusion-webui root folder also.
insightface==0.7.3
onnx==1.14.0
onnxruntime==1.15.0
opencv-python==4.7.0.72
ifnude
cython

**Comment by Steebeeweebee** [comment]
Been there, tried that - You too?

### **For Python noobs on Windows 10 like me - Possible solution why Roop does not start in A1111 in Windows 10/11**  - TLDR: You might be missing a correct Python installation on your computer...
Perhaps @s0md3v can make good use of this info and my very limited knowledge of Python maybe helped to look at it from another perspective. @s0md3v - Thank you for this awesome extension!

-------
For errors like:

- ModuleNotFoundError: No module named 'nameofthemodule, for example the common ones like No module named '**insightface**', No module named '**_socket**', No module named '**ifnude**' etc.

- **Protobuf** parsing failed

- and so on

-------
### **Possible Noob Explanation*, beware, because it's a silly one*:
On A1111's [main page](https://github.com/AUTOMATIC1111/stable-diffusion-webui), Nvidia card owners are likely to follow the quite comfortable method under

_"Installation on Windows 10/11 with NVidia-GPUs using release package"_

and this could lead to a misunderstanding, especially if you do not have Python correctly installed! In my case I had been tesing around here and there, installing and uninstalling stuff, including conda, miniconda and all that good stuff. What a mess. When you use this method it sounds (and is) nice but you might be missing crucial parts. The **sd.webui.zip** is neat but only contains folders with A1111's Web-Ui and Python elements...and that **does not automatically mean that Python is correctly installed on your computer.** It will try to run but there will be plenty of errors, as paths are misleading or just not there, parts are missing left and right, reinstalling individual elements with "pip blabla" will break other things etc.  

-------

### >>> **Solution**: 
Make sure you have Python 3.10.6,  downloaded and correctly installed before getting Roop etc., or

### >>> **Easiest Solution**:
Just follow the instructions, that's it!

I recommend to:

1. start from scratch and to follow the few instructions mentioned on A1111's [main page](https://github.com/AUTOMATIC1111/stable-diffusion-webui) under "**Automatic Installation on Windows**"
2. These instructions include the Python 3.10.6 installation (so you won't miss that step which could redress lots of things by just (re-)installing the thing)
3. Get a fresh A1111 installation
4. get **Roop** on it
5. by launching **update.bat** you'll see that there will be plenty of things happening that you haven't seen before (some downloads here and there)
6. then launch with **run.bat** and welcome to that error-free launch sequence with Roop showing up in your SD-WebUi. 
7. Enjoy ;)

#lessonslearned

**Comment by mdkberry** [comment]
I have windows 10 with python 3.10.6 in a conda environment and installing roop from the extension it did not show up in SD after restarting webgui from inside SD. I also had the message _""ModuleNotFoundError: No module named 'insightface'""_

The fix was I had to actually exit out of SD completely and go back in. It then installs stuff, but re-installs it every restart. 

> Installing requirements
> 
> Checking roop requirements
> Install insightface==0.7.3
> Installing sd-webui-roop requirement: insightface==0.7.3
> Install onnx==1.14.0
> Installing sd-webui-roop requirement: onnx==1.14.0
> Install onnxruntime==1.15.0
> Installing sd-webui-roop requirement: onnxruntime==1.15.0
> Install opencv-python==4.7.0.72
> Installing sd-webui-roop requirement: opencv-python==4.7.0.72

but it is available after that

**Comment by taxen** [comment]
I think the screenshot is not so kind. I thought a new tab would appear just below model and VAE select list if one set so. Instead, this extension appears in "From Text" tab, just below "Steps animation" list, as shown the attached image.
Just in case someone is looking for it in a wrong place.

![image](https://github.com/s0md3v/sd-webui-roop/assets/3875423/56647d45-16a1-4f1c-8f87-451c9e4c0535)

Also, model(s) must be placed in <webui_dir>/models/roop/, not <webui_dir>/extensions/sd-webui-roop/models/roop/, where the installer installs anyway. The automatically downloaded file "inswapper_128.onnx" must be move to the right place, which is in <webui_dir>/models/roop/ as instructed.

Make sure to run ```pip install insightface==0.7.3``` before putting the git URL and pushing Install button.

**Comment by frankomondo** [comment]
I tried everything but I just can't get it to appear in the UI using Nvidia RTX 3060
this is the error
2023-08-24 20:10:25,306 - roop - INFO - roop v0.0.2
*** Error loading script: swapper.py
    Traceback (most recent call last):
      File "C:\a1111\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\a1111\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\a1111\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 13, in <module>
        import onnxruntime
    ModuleNotFoundError: No module named 'onnxruntime'

**Comment by jyotirmoypaul** [comment]
If nothing works, then the last solution is to keep a Backup of all your Models and Extensions. Then make a fresh installation of the latest Automatic1111.
